import type { Metadata } from "next";
import Navigation from "@/HOC/navigation";
import "../styles/globals.scss";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customFont = localFont({
  src: "../assets/fonts/SourceSansPro-Regular.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <Navigation>
          {children}
        </Navigation>
      </body>
    </html>
  );
}
